spring:
  application:
    name: todo-list-spring-react-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  flyway:
    url: jdbc:postgresql://localhost:5432/todo_db
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: postgres
    password: postgres

logging:
  level:
    "org.springframework.context": DEBUG
    "org.springframework.beans.factory": DEBUG

frontend:
  admin:
    url: "${FRONTEND_ADMIN_URL:http://localhost:5173}"

